#!/bin/sh

LOGF=/home/mirror-daemon/rsync-to-xyzzy.log

if [ ! -f $LOGF ]; then
    touch $LOGF
fi
chmod ug+w $LOGF
exec >>$LOGF 2>>$LOGF

echo
echo "====================================================================="
echo "Starting at $(date) with args: $@"
echo "====================================================================="
echo

REMOTE=ryan52@dev.freegeek.org
PATH=$PATH:~/bin/
cd
wget http://dev.freegeek.org/~ryan52/devel_data/version -O /var/tmp/version.new
mkdir /tmp/rsync-to-xyzzy || { echo "rsync-to-xyzzy is already running"; exit 1; }
if [ "$1" = "--force" -o "$1" = "-f" -o "$1" = "force" ] || [ ! -f devel_data/version ] || ! diff /var/tmp/version.new devel_data/version; then
    under-myagent rsync --progress --delete-excluded -azv $REMOTE:public_html/devel_data/ devel_data/
    RETURN="$?"
else
    RETURN=0
fi
rmdir /tmp/rsync-to-xyzzy

echo
echo "====================================================================="
echo "Finished with $RETURN at $(date)"
echo "====================================================================="
echo

exit $RETURN
