#!/bin/sh

PROGRAM="$1"
shift
FILE=$(mktemp)
ssh-agent > $FILE
. $FILE
NORMAL=$(dirname $(readlink -f $0))/scp_key
if [ -f "$NORMAL" ]; then
    ssh-add "$NORMAL"
elif [ "$(hostname)" = "borked" -o "$(hostname)" = "oahu" -o "$(hostname)" = "chaos" ]; then
    ssh-add /home/ryan52/.ssh/scp_key
elif [ "$(hostname)" = "xyzzy" ]; then
    ssh-add /home/ryan52/.ssh/freegeek-git
else
    echo "WTF is this machine?!?!"
    exit 1
fi
"$PROGRAM" "$@"
RET=$?
kill $SSH_AGENT_PID
exit $RET
