source 'https://rubygems.org'
ruby '1.9.3'
gem 'rails', '~>3.0.0'
gem 'nokogiri'
gem 'barby'
gem 'rmagick'
gem 'json'
gem 'thin'
gem 'gnuplot'
gem 'pg'
gem 'pdf-writer'
gem 'bluecloth'
gem 'rdoc'
gem 'soap4r', :git => 'https://github.com/felipec/soap4r.git'
gem 'prawn'