source 'https://rubygems.org'
ruby '1.9.3'
gem 'rails', '~>3.0.0'
gem 'nokogiri'
gem 'barby'
gem 'rmagick'
gem 'json'
gem 'thin'
gem 'gnuplot'
gem 'pg'
gem 'pdf-writer'
gem 'bluecloth'
gem 'rdoc'
gem 'soap4r', :git => 'https://github.com/felipec/soap4r.git'
gem 'prawn'
gem 'validates_existence', '>= 0.4'
gem 'will_paginate', '~> 3.0'
gem 'dynamic_form'
gem 'country_select'
gem 'jbuilder'

group :test do
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'poltergeist'
end
