#!/bin/bash

# Load the rvm config
. ~/.rvm/environments/ruby-1.9.3-p484

cd ~/deploy

# Put the application into maintenance mode
touch tmp/stop.txt

bundle install

export RAILS_ENV=production
rake db:backup
rake db:migrate

touch tmp/restart.txt
rm tmp/stop.txt
