#!/bin/bash
# rotate logs before dumping
/usr/sbin/logrotate -f /usr/local/backup/database_logrotate_daily.conf
# dump the database, data only 
su - postgres -c "pg_dump -a -D fgdb.rb | gzip > /usr/local/backup/database_daily_data.sql.gz"
# dump the database, schema only 
su - postgres -c "pg_dump -s -D fgdb.rb > /usr/local/backup/database_daily_schema.sql"
#:?: maybe you mirror you db like this:
#nice scp -i /root/.ssh/db_mirror /usr/local/backup/database_daily_data.sql.gz mirror:/usr/local/backup/
#nice scp -i /root/.ssh/db_mirror /usr/local/backup/database_daily_schema.sql mirror:/usr/local/backup/

# note: rsyncing to another server might be done best in your
# hourly cron job, as we do at Free Geek
