#!/bin/bash
/usr/sbin/logrotate -f /usr/local/backup/database_logrotate_daily.conf
su - postgres -c "pg_dump -a -D fgdb.rb | gzip > /usr/local/backup/database_daily_data.sql.gz"
su - postgres -c "pg_dump -s -D fgdb.rb > /usr/local/backup/database_daily_schema.sql"
#nice scp -i /root/.ssh/db_mirror /usr/local/backup/database_daily_data.sql.gz pollen:/usr/local/backup/
#nice scp -i /root/.ssh/db_mirror /usr/local/backup/database_daily_schema.sql pollen:/usr/local/backup/
