#!/usr/bin/ruby

ENV['RAILS_ENV']="development"

require File.dirname(__FILE__) + '/../../config/boot'
require File.expand_path(File.dirname(__FILE__) + "/../../config/environment")

SpecSheet.connection.execute("DELETE FROM spec_sheets")
SpecSheet.connection.execute("ALTER SEQUENCE spec_sheets_id_seq RESTART WITH 1")

ARGV.each {|x|
stuff = File.open(x).read
hash = {:lshw_output => stuff, :type_id => 1, :action_id => 1, :contact_id => 1, :notes => ""}
ss = SpecSheet.new(hash)
ss.save!
puts x.sub(/.xml/, "") + " - " + ss.id.to_s
}
