#!/bin/bash

cd `dirname $0`

rm *.xml
rm xml.tgz

RAND="$1"
if [ -z "$RAND" ]; then
    RAND=19
fi

for i in `echo "SELECT id FROM systems WHERE extract( second from updated_at )::integer = $RAND LIMIT 10;" | psql fgdb_production | grep 40`; do
    echo "SELECT lshw_output FROM spec_sheets WHERE system_id = $i LIMIT 1;" | psql fgdb_production | grep "^ " | grep -v lshw_output | sed 's/^ //' > $i.xml
    if ! xmlstarlet val $i.xml >/dev/null; then
        rm $i.xml
    fi
done

tar czvf xml.tgz *.xml >/dev/null
scp xml.tgz llama.freegeek.org:public_html/ >/dev/null
rm *.xml

echo "Now download it at http://llama.freegeek.org/~$USER/xml.tgz"

