#!/bin/bash

cd `dirname $0`

if ! [ -f xml.tgz ]; then
    echo "You need to get the xml.tgz"
    exit 1
fi

tar xzvf xml.tgz >/dev/null

#if [ `ls *.xml | wc -l` != 10 ]; then
#    echo "There should be 10 xml files"
#    exit 1
#fi

./add_report $i *.xml

rm *.xml
