json.manufacturer drive.manufacturer
json.id drive.id
json.model drive.model
json.serial drive.serial
json.size drive.size
json.manufacture_date drive.manufacture_date
json.firmware_version drive.firmware_version
json.physical_form_factor drive.physical_form_factor
json.interface_type drive.interface_type
json.label_image_url nil
json.board_image_url nil
json.board_status drive.board_status
