-- Tables (and table modifications) for selling items

-- change set 30sep06
alter TABLE discount_schedules
  rename column name to short_name;

-- change set 30sep06
--alter table sale_txns
--  drop column is_refund;
--alter table sale_txn_lines
--  drop column is_refund;
 

-- change set 29sep06
--alter table sale_txns
--  add column discount_schedule_id integer default 1 not null,
--  drop column tax_amount;
--alter table sale_txn_lines
--  drop column taxable,
--  drop column tax_applied;
--alter table sale_txn_lines
--  rename column base_price to unit_price;
--alter table forsale_items
--  drop column taxable;
--
--CREATE TABLE discount_schedules (
--    id serial NOT NULL,
--    name character varying(25),
--    donated_item_rate numeric(10,2) DEFAULT 0,
--    resale_item_rate numeric(10,2) DEFAULT 0,
--    description character varying(100),
--    lock_version integer DEFAULT 0 NOT NULL,
--    updated_at timestamp with time zone DEFAULT now(),
--    created_at timestamp with time zone DEFAULT now(),
--    created_by bigint DEFAULT 1 NOT NULL,
--    updated_by bigint DEFAULT 1 NOT NULL
--);
--
--COMMENT ON TABLE discount_schedules IS 'discount schedules and their discount percents';


-- first pass

--CREATE TABLE source_types (
--    id serial NOT NULL,
--    description character varying(100),
--    lock_version integer DEFAULT 0 NOT NULL,
--    updated_at timestamp with time zone DEFAULT now(),
--    created_at timestamp with time zone DEFAULT now(),
--    created_by bigint DEFAULT 1 NOT NULL,
--    updated_by bigint DEFAULT 1 NOT NULL
--);
--
--COMMENT ON TABLE source_types IS 'sources of items for sale: store, other';
--
--CREATE TABLE forsale_items (
--    id serial NOT NULL,
--    source_type_id integer,
--    description character varying(100) not null,
--    price numeric(10,2) DEFAULT 9.99,
--    onhand_qty integer,
--    taxable boolean DEFAULT false not null,
--    lock_version integer DEFAULT 0 NOT NULL,
--    updated_at timestamp with time zone DEFAULT now(),
--    created_at timestamp with time zone DEFAULT now(),
--    created_by bigint DEFAULT 1 NOT NULL,
--    updated_by bigint DEFAULT 1 NOT NULL
--);
--COMMENT ON TABLE forsale_items IS 'items for sale; not intended as inventory';
--
--create table till_handlers (
--    id serial NOT NULL,
--    description character varying(100) not null,
--    contact_id integer NOT NULL,
--    can_alter_price boolean default false not null,
--    lock_version integer DEFAULT 0 NOT NULL,
--    updated_at timestamp with time zone DEFAULT now(),
--    created_at timestamp with time zone DEFAULT now(),
--    created_by bigint DEFAULT 1 NOT NULL,
--    updated_by bigint DEFAULT 1 NOT NULL
--);
--COMMENT ON TABLE till_handlers IS 'identifies those who operate the till';
--
--create table sale_txns (
--    id serial NOT NULL,
--    description character varying(100) not null,
--    contact_id integer NOT NULL,
--    till_handler_id integer NOT NULL,
--    payment_method_id integer NOT NULL,
--    gross_amount numeric(10,2) not null,
--    discount_amount numeric(10,2),
--    tax_amount numeric(10,2),
--    amount_due numeric(10,2) not null,
--    is_refund boolean,
--    comments character varying(100) not null,
--    lock_version integer DEFAULT 0 NOT NULL,
--    updated_at timestamp with time zone DEFAULT now(),
--    created_at timestamp with time zone DEFAULT now(),
--    created_by bigint DEFAULT 1 NOT NULL,
--    updated_by bigint DEFAULT 1 NOT NULL
--);
--COMMENT ON TABLE sale_txns IS 'each record represents one sales transaction';
--
--create table sale_txn_lines (
--    id serial NOT NULL,
--    sale_txn_id integer NOT NULL,
--    forsale_item_id integer NOT NULL,
--    base_price numeric(10,2) not null,
--    quantity integer NOT NULL,
--    extended_price numeric(10,2) not null,
--    discount_applied numeric(10,2),
--    taxable boolean DEFAULT false not null,
--    tax_applied numeric(10,2),
--    sale_txn_amount numeric(10,2) not null,
--    is_refund boolean,
--    comments character varying(100) not null,
--    lock_version integer DEFAULT 0 NOT NULL,
--    updated_at timestamp with time zone DEFAULT now(),
--    created_at timestamp with time zone DEFAULT now(),
--    created_by bigint DEFAULT 1 NOT NULL,
--    updated_by bigint DEFAULT 1 NOT NULL
--);
--COMMENT ON TABLE sale_txn_lines IS 'one record is one detail line in a sales transaction';
