#!/bin/sh

# depends on daemon, downloadable here: http://git.ryan52.info/redirect/daemon.c

case "$1" in
    start)
	sudo su - -c "daemon /home/cruise/cruise/cruise start -p 8000 -b 127.0.0.1 -d" cruise
	;;
    stop)
	kill `ps aux | awk '/^cruise/{print $2}'`
	THING=0
	while [ $THING -lt 5 ] && [ -n "$(ps aux | awk '/^cruise/{print $2}')" ]; do
	    THING=$(( $THING + 1 ))
	    sleep 1
	done
	kill -s 9 `ps aux | awk '/^cruise/{print $2}'`
	;;
    restart)
	$0 stop
	$0 start
	;;
    *)
	echo "usage: $0 start|stop|restart"
	;;
esac
