module SystemHelper
  # this will take over PrintmeHelper soon

  class CommonParser
    attr_reader :string, :system

    def initialize(in_string, in_system)
      @string = in_string
      @system = in_system
      do_work
    end
  end

  class SystemParserException < Exception
  end

  class LshwSystemParser < CommonParser
    include XmlHelper

    def self.match_string
      "generated by lshw"
    end

    attr_reader :parser # REMOVEME

    def do_work
      @parser = load_xml(@string) or raise SystemParserException
      # this will parse @string, and set @system.memories/etc
    end
  end

  class PlistSystemParser < CommonParser
    def self.match_string
      "DOCTYPE plist"
    end

    def do_work
      raise
    end
  end

  class SystemParser
    Parsers = [PlistSystemParser, LshwSystemParser]

    attr_accessor :processors, :l2_cache, :bios, :usb_supports, :drive_supports
    attr_accessor :memories, :harddrives, :opticals, :pcis
    attr_accessor :system_model, :system_serial_number, :system_vendor, :mobo_model, :mobo_serial_number, :mobo_vendor, :macaddr
    attr_accessor :model, :vendor, :serial_number

    attr_reader :string, :parser, :myparser

    def SystemParser.parse(in_string)
      sp = nil
      begin
        sp = SystemParser.new(in_string)
      rescue SystemParserException
        return false
      end
      return sp
    end

    def initialize(in_string)
      @string = in_string
      @parser = Parsers.select{|x| @string.match(/#{x.match_string}/)}.first
      raise SystemParserException if @parser.nil?
      @myparser = @parser.new(@string, self) # TODO: does ruby's garbage collection handle these circularly referenced objects? I would think it probably doesn't...I should fix this fer sure.
    end
  end
end
