#!/bin/bash
#KEEP  ^^^^ as bash. There is a bashism in here.

set -e

if [ "$1" = "--noexec" ] || [ "$1" = "--no-exec" ]; then
    NOEXEC="echo"
fi

cd `dirname $0`
cd ../..

if [ ! -d trunk ]; then
    pwd
    echo "Where's trunk?"
    exit 1
fi

LIST="$(ls {branches,tags}/*/db/*.sql.gz 2>/dev/null)"

if [ -z "$LIST" ]; then
    echo "none found...exiting"
    exit
fi

awk -F '/' '{sub("es$", "", $1); sub("s$", "", $1); print "Deleting database dumps from the", $2, $1}' <<EOF
${LIST}
EOF

echo
echo
echo

for i in $LIST; do
    $NOEXEC svn rm $i
done

echo
echo
echo

if [ -z "$NOEXEC" ]; then
    echo -n "Continue? (say YES) "
    read yesno

    if [ "$yesno" != "YES" ]; then
        echo "Aborted"
        exit
    fi
fi


$NOEXEC svn ci $LIST -m "removed database dumps from tags and branches"
echo
