#!/bin/sh

num=100

cd results
echo -n > bad
for i in `seq $num`; do
    x=$((i * 50))
    echo $x
    set -x
    wget http://home.ryan52.info:3000/spec_sheets/show/$x -O $x.mine
    wget http://data/spec_sheets/show/$x -O $x.good
    diff $x.good $x.mine
    set +x
    echo
    echo
    echo -n "Is it good? [y] "
    read YESNO
    if [ "$YESNO" = "" ]; then
    YESNO=y
    fi
    case $YESNO in
    y*)
        ;;
        *)
            echo $x >> bad
                ;;
    esac
done
