#!/bin/sh

sudo passenger-status
echo "$(tput bold)$(tput setab 4)$(tput setaf 3)----------- Database Connections -----------$(tput init)"
echo 'SELECT * FROM pg_stat_activity;' | psql fgdb_production
