#!/bin/sh

set -e
BACKUP_SERVER=peabody
INCOME=/usr/local/zhora-backup/incoming/
LIST=$(ls $INCOME)
DEST=root@${BACKUP_SERVER}:/srv/data-extras/data-backups/

if [ ! -z "$LIST" ]; then
   rsync -q -e 'ssh -i /root/.ssh/backup_key2' -Hqza $INCOME  $DEST
   cd $INCOME
   for FILE in $LIST; do
      rm -fr $FILE
   done
fi
