#!/bin/sh

# all I have to say is "git log release_1.0.17.." and "bzr
# missing". if subversion isn't as dumb as I think it is, then please
# correct me and tell me the easy way to do this.

# THIS SCRIPT IS STUPID AND (LIKE SUBVERSION) JUST DOESN'T WORK!!!

set -e

cd `dirname $0`/..

cd ..
svn up
cd $OLDPWD

if [ $# -lt 1 ]; then
    SVNOPTS=--verbose
else
    SVNOPTS="$@"
fi

echo "SVNOPTS: $SVNOPTS"

OTHER_BRANCH_NUMBER=$(ls ../branches/ | grep release_1.0. | sed 's/release_1.0.//' | sort -n | tail -1)
OTHER_BRANCH_COMMIT=$(svn log --verbose --stop-on-copy ../branches/release_1.0.$OTHER_BRANCH_NUMBER | grep -A 1 -E "^\-+$"  | grep -Ev "^\-+$" | tail -1 | awk '{print $1}')
IN_TRUNK=$(svn log $SVNOPTS -r $OTHER_BRANCH_COMMIT:HEAD)
cd ../branches/release_1.0.$OTHER_BRANCH_NUMBER
IN_BRANCH=$(svn log -r $OTHER_BRANCH_COMMIT:HEAD)
cd $OLDPWD

if test -z "$IN_BRANCH"; then
cat - | less <<EOF
Changes (seemingly) only in branch:
$(cat - | sed 's/^/ /g' <<FEOF
$IN_BRANCH
FEOF
)

Changes only in trunk:
$(cat - | sed 's/^/ /g' <<FEOF
$IN_BRANCH
FEOF
)
EOF
else
    cat - | less <<EOF
$IN_TRUNK
EOF
fi