#!/bin/sh

# all I have to say is "git log release_1.0.17.." and "bzr
# missing". if subversion isn't as dumb as I think it is, then please
# correct me and tell me the easy way to do this.

# THIS SCRIPT IS STUPID AND (LIKE SUBVERSION) JUST DOESN'T WORK!!!

set -e

cd `dirname $0`/..

cd ..
svn up
cd $OLDPWD

if [ $# -lt 1 ]; then
    SVNOPTS=--verbose
else
    SVNOPTS="$@"
fi

echo "SVNOPTS: $SVNOPTS"

OTHER_BRANCH_NUMBER=$(ls ../branches/ | grep release_1.0. | sed 's/release_1.0.//' | sort -n | tail -1)
OTHER_BRANCH_COMMIT=$(svn log ../branches/release_1.0.$OTHER_BRANCH_NUMBER | grep -B 2 "branching" | awk '{print $1; exit;}')
IN_TRUNK=$(svn log $SVNOPTS -r $OTHER_BRANCH_COMMIT:HEAD)
cd ../branches/release_1.0.$OTHER_BRANCH_NUMBER
IN_BRANCH=$(svn log -r $OTHER_BRANCH_COMMIT:HEAD)
cd $OLDPWD
IGNORE=$(awk 'BEGIN{first=true} /merge r[0-9]+/{if(first != true) printf ","; printf substr($0, match("merge r[0-9]", $0) + 7, 5); first=false}' <<EOF
$IN_BRANCH
EOF
)

if test -n "$IN_BRANCH"; then
less <<EOF
Changes (seemingly) only in branch:
$(sed 's/^/ /g' <<FEOF
$IN_BRANCH
FEOF
)

Changes only in trunk:
$(sed 's/^/ /g' <<FEOF | awk -v blah=$IGNORE -f ./script/list_changes.awk
$IN_TRUNK
FEOF
)
EOF
else
less <<EOF
$IN_TRUNK
EOF
fi