#!/bin/sh

set -e

git checkout devel
git merge master
sed -i s/UNRELEASED/released/g ChangeLog
dch -c ChangeLog -i --dist UNRELEASED ""
sed -i '/^  \* $/ d' ChangeLog
git add ChangeLog
git commit -m "add new, empty changelog entry"
git push fg devel:devel

