#!/bin/sh

for i in 0 1 2; do
    echo "Restarting $i"
    sudo /usr/bin/thin restart -C /etc/thin/fgdb.yml -o $i >/dev/null 2>/dev/null
    echo "Checking if file exists"
    while [ ! -e /tmp/thin.$i.sock ]; do echo "It doesn't, napping"; sleep 0.5; echo "Checking again"; done
    echo "It does now"
    echo "Starting socat for $i"
    socat TCP4-LISTEN:500$i,reuseaddr,fork UNIX-CONNECT:/tmp/thin.$i.sock &
    SOCAT=$!
    echo "Trying to download"
    while ! curl http://localhost:500$i/ 2>/dev/null | grep -q "Free Geek"; do echo "It failed, napping"; sleep 0.5; echo "Checking again"; done
    echo "It worked"
    echo "Killing socat"
    kill $SOCAT
    wait $SOCAT
    echo
    echo
    echo
done
