#!/bin/sh

for i in 0 1 2; do
    echo "Restarting $i"
    sudo /usr/bin/thin restart -C /etc/thin/fgdb.yml -o $i >/dev/null 2>/dev/null
    echo "Checking if file exists"
    while [ ! -e /tmp/thin.$i.sock ]; do echo "It doesn't, napping"; sleep 0.5; echo "Checking again"; done
    echo "Starting socat for $i"
    socat TCP4-LISTEN:3000,reuseaddr,fork UNIX-CONNECT:/tmp/thin.$i.sock &
    echo "Trying to download"
    while ! curl http://localhost:3000/ >/dev/null 2>/dev/null; do echo "It failed, napping"; sleep 0.5; echo "Checking again"; done
    echo "Killing socat"
    kill %1
    wait
    echo
    echo
    echo
done
