#!/bin/sh

set -e
set -x

if [ "$(cat .git/HEAD)" != "ref: refs/heads/master" ]; then
    echo "Need to be on the master branch" >&2
    exit 1
fi

if [ ! -f .git/refs/remotes/fg/master -o ! -f .git/refs/remotes/origin/master ]; then
    echo "Need to have a fg and an origin remote branch" >&2
    exit 1
fi

git fetch origin
git pull
dch -r -c ChangeLog ""
git add ChangeLog
git commit -m "releasing"
VERSION=$(dpkg-parsechangelog -lChangeLog | awk -F": " '/^Version: /{print $2}')
git checkout -b release_$VERSION
wget http://dev.freegeek.org/~ryan52/devel_data/version -O db/branch_devel_data_version
touch db/branch_devel_data_version
git add db/branch_devel_data_version
git commit -m "add devel data version number to branch"
git tag $VERSION
git push fg master:master
git push fg release_$VERSION:release_$VERSION
git config branch.release_$VERSION.remote origin
git config branch.release_$VERSION.merge release_$VERSION
git push fg --tags
git checkout master
git merge release_$VERSION
git rm db/branch_devel_data_version
git commit -m "remove devel data version for master"
./dpkg-parsechangelog | ssh xyzzy.ryan52.info mail -s "FGDB.rb version $VERSION released" coders@lists.freegeek.org
dch -c ChangeLog -i --dist UNRELEASED ""
git add ChangeLog
git commit -m "add new, empty changelog entry"
git push fg master:master
