#!/bin/sh

set -e

SCRIPT=`dirname $0`/generate_volskedj.rb
OUTPUT=$($SCRIPT | tee -a /var/www/fgdb.rb/log/volskedj.log)
MAILTO=$(/var/www/fgdb.rb/script/runner 'puts Default["management_mailing_list"]')
CC_MAILTO=dbadmin

if [ -n "$OUTPUT" ]; then
   cat - <<EOF | mail -s 'Conflicts in automatic volunteer schedule' -c "$CC_MAILTO" "$MAILTO"
The following errors were encountered while automatically generating the volunteer schedule:
${OUTPUT}
EOF
fi
