#!/bin/sh

set -e

if [ -z "$1" ]; then
   echo "Usage: $(basename $0) project" >/dev/stderr
   exit 1
fi

cd $(dirname $(readlink -f $0))/../../

if [ "$1" = "-f" ]; then
    FORCE=true
    shift
fi

if [ ! -d fgdb.rb ]; then
    echo "You need to have an fgdb.rb directory in $(pwd)" >/dev/stderr
    exit 1
fi

if [ -d $1 ]; then
    if [ "$FORCE" = "true" ]; then
        rm -fr $1
    else
        echo "Project $1 already exists in $(pwd)" >/dev/stderr
        echo "Please remove it first" >/dev/stderr
        exit 1
    fi
fi

rails $1
cd $1
git init
echo "*~" > .gitignore
git add .gitignore
git commit -m "[$(basename $0)] added .gitignore"
git add .
git commit -m "[$(basename $0)] ran rails"
git rm README
git commit -m "[$(basename $0)] removed README"

# generated with: for i in `find . -type l`; do echo $(readlink $i) $i; done | while read a b; do echo rm -fr $b; echo mkdir -p $(dirname $a); echo ln -sf $a $b; done > my_script

rm -fr ./vendor/plugins/validates_existence
mkdir -p ./vendor/plugins
ln -sf ../../fgdb.rb/vendor/plugins/validates_existence/ ./vendor/plugins/validates_existence
rm -fr ./vendor/plugins/dhtml-calendar
mkdir -p ./vendor/plugins
ln -sf ../../fgdb.rb/vendor/plugins/dhtml-calendar/ ./vendor/plugins/dhtml-calendar
rm -fr ./vendor/activerecord
mkdir -p ./vendor
ln -sf /usr/share/rails/activerecord ./vendor/activerecord
rm -fr ./vendor/activesupport
mkdir -p ./vendor
ln -sf /usr/share/rails/activesupport ./vendor/activesupport
rm -fr ./vendor/activeresource
mkdir -p ./vendor
ln -sf /usr/share/rails/activeresource ./vendor/activeresource
rm -fr ./vendor/actionmailer
mkdir -p ./vendor
ln -sf /usr/share/rails/actionmailer ./vendor/actionmailer
rm -fr ./vendor/actionpack
mkdir -p ./vendor
ln -sf /usr/share/rails/actionpack ./vendor/actionpack
rm -fr ./vendor/railties
mkdir -p ./vendor
ln -sf /usr/share/rails/railties ./vendor/railties
rm -fr ./vendor/activemodel
mkdir -p ./vendor
ln -sf /usr/share/rails/activemodel ./vendor/activemodel
rm -fr ./vendor/rails
mkdir -p ./vendor
ln -sf /usr/share/rails ./vendor/rails
rm -fr ./tmp
mkdir -p .
ln -sf fgdb.rb/tmp ./tmp
rm -fr ./log
mkdir -p .
ln -sf fgdb.rb/log ./log
rm -fr ./public
mkdir -p .
ln -sf fgdb.rb/public ./public
rm -fr ./Rakefile
mkdir -p .
ln -sf fgdb.rb/Rakefile ./Rakefile
rm -fr ./lib
mkdir -p .
ln -sf fgdb.rb/lib ./lib
rm -fr ./script/server
mkdir -p ./script
ln -sf ../fgdb.rb/script/server ./script/server
rm -fr ./script/find_dups
mkdir -p ./script
ln -sf ../fgdb.rb/script/find_dups ./script/find_dups
rm -fr ./script/version
mkdir -p ./script
ln -sf ../fgdb.rb/script/version ./script/version
rm -fr ./script/do_i_have_everything_installed_right
mkdir -p ./script
ln -sf ../fgdb.rb/script/do_i_have_everything_installed_right ./script/do_i_have_everything_installed_right
rm -fr ./script/make_admin
mkdir -p ./script
ln -sf ../fgdb.rb/script/make_admin ./script/make_admin
rm -fr ./script/load_devel_data
mkdir -p ./script
ln -sf ../fgdb.rb/script/load_devel_data ./script/load_devel_data
rm -fr ./doc
mkdir -p .
ln -sf fgdb.rb/doc ./doc
rm -fr ./config/environments
mkdir -p ./config
ln -sf ../fgdb.rb/config/environments ./config/environments
rm -fr ./config/environment.rb
mkdir -p ./config
ln -sf ../fgdb.rb/config/environment.rb ./config/environment.rb
rm -fr ./config/routes.rb
mkdir -p ./config
ln -sf ../fgdb.rb/config/routes.rb ./config/routes.rb
rm -fr ./config/boot.rb
mkdir -p ./config
ln -sf ../fgdb.rb/config/boot.rb ./config/boot.rb
rm -fr ./config/initializers
mkdir -p ./config
ln -sf ../fgdb.rb/config/initializers ./config/initializers
rm -fr ./config/database.yml-example
mkdir -p ./config
ln -sf ../fgdb.rb/config/database.yml-example ./config/database.yml-example
rm -fr ./config/database.yml
mkdir -p ./config
ln -sf ../fgdb.rb/config/database.yml ./config/database.yml
rm -fr ./db
mkdir -p .
ln -sf fgdb.rb/db/ ./db
rm -fr ./app/models/role.rb
mkdir -p ./app/models
ln -sf ../../fgdb.rb/app/models/role.rb ./app/models/role.rb
rm -fr ./app/models/contact.rb
mkdir -p ./app/models
ln -sf ../../fgdb.rb/app/models/contact.rb ./app/models/contact.rb
rm -fr ./app/models/user.rb
mkdir -p ./app/models
ln -sf ../../fgdb.rb/app/models/user.rb ./app/models/user.rb
rm -fr ./app/views/layouts
mkdir -p ./app/views
ln -sf ../../fgdb.rb/app/views/layouts/ ./app/views/layouts
rm -fr ./app/views/sessions
mkdir -p ./app/views
ln -sf ../../fgdb.rb/app/views/sessions/ ./app/views/sessions
rm -fr ./app/views/sidebar_links
mkdir -p ./app/views
ln -sf ../../fgdb.rb/app/views/sidebar_links/ ./app/views/sidebar_links
rm -fr ./app/helpers/application_helper.rb
mkdir -p ./app/helpers
ln -sf ../../fgdb.rb/app/helpers/application_helper.rb ./app/helpers/application_helper.rb
rm -fr ./app/controllers/application.rb
mkdir -p ./app/controllers
ln -sf ../../fgdb.rb/app/controllers/application.rb ./app/controllers/application.rb
rm -fr ./app/controllers/sidebar_links_controller.rb
mkdir -p ./app/controllers
ln -sf ../../fgdb.rb/app/controllers/sidebar_links_controller.rb ./app/controllers/sidebar_links_controller.rb
rm -fr ./app/controllers/sessions_controller.rb
mkdir -p ./app/controllers
ln -sf ../../fgdb.rb/app/controllers/sessions_controller.rb ./app/controllers/sessions_controller.rb

git add .
git commit -m "[$(basename $0)] set up symlinks to fgdb.rb"
rm -fr ./fgdb.rb
ln -sf ../fgdb.rb ./fgdb.rb
echo "fgdb.rb" >> .gitignore
git add .gitignore
git commit -m "[$(basename $0)] added the fgdb.rb symlink to .gitignore"

echo "name: $1" > ./app.yaml
git add ./app.yaml
git commit -m "[$(basename $0)] added app.yaml"

for i in `find . -type d -empty | grep -v "^./.git/"`; do
    touch $i/.gitignore
    git add $i/.gitignore
done
git commit -m "[$(basename $0)] added empty directories"
