#!/bin/bash

set -e
set -x
set -u

export RAILS_ENV=development

TMP=$(mktemp -d /tmp/fgdb.testing.script.XXXXXXXXXX)
cd $TMP
scp -i ~/.ssh/scp_key tulip:/usr/local/arik/database.sql.gz ./
dropdb fgdb_$RAILS_ENV || true
gunzip database.sql.gz 
#createdb fgdb_$RAILS_ENV
#psql fgdb_$RAILS_ENV < database.sql
sed -i "s/fgdb_production/fgdb_$RAILS_ENV/g" database.sql
psql < database.sql
if hostname -f | grep -q fglan; then
    git clone http://dev.freegeek.org/~ryan52/git/fgdb.rb trunk
else
    git clone git://git.ryan52.info/git/fgdb.rb trunk
fi
cd trunk
cp config/database.yml-example config/database.yml
ln -s /usr/share/rails vendor/rails
rake db:migrate
cd ../
rm -f database.sql
dropdb fgdb_$RAILS_ENV
rm -fr trunk
cd /
rm -fr $TMP
