#!/bin/sh

cd `dirname $0`/..
./script/runner 'def die(str); puts str; exit 1; end; Worker.find(:all).select{|x| !x.virtual}.each{|x| puts "Checking worker ##{x.id}"; die("Worker ##{x.id} is not valid: #{x.errors.full_messages}") if ! x.valid?}; WorkersWorkerType.find(:all).each{|x| puts "Checking worker ##{x.worker.id}"; die("Worker ##{x.worker.id} is not valid: #{x.errors.full_messages}") if ! x.valid?}; puts "Looks good.";'
