#!/bin/sh

cd `dirname $0`/..
if [ $(dpkg-parsechangelog -lChangeLog | awk '/^Distribution: /{print $2}') = "UNRELEASED" ]; then
    echo "UNRELEASED"
    exit
fi
dpkg-parsechangelog -lChangeLog | awk '/^Version: /{print $2}'
