#!/bin/sh

cd `dirname $0`/..
VERSION=$(head -1 ChangeLog | awk '{print $2}' | sed 's/[()]//g')
DIST=$(head -1 ChangeLog | awk '{print $3}' | sed 's/[;]//g')
if [ "$DIST" = "UNRELEASED" ]; then
    echo "$VERSION (UNRELEASED)"
else
    echo "$VERSION"
fi

