class SoManyForeignKeysToAdd < ActiveRecord::Migration
  def self.up
    add_foreign_key( "contact_method_types", ["parent_id"], "contact_method_types", ["id"], :name => "contact_method_types_parent_id_fk" )
    add_foreign_key( "contact_types_contacts", ["contact_id"], "contacts", ["id"], :name => "contact_types_contacts_contacts_fk" )
    add_foreign_key( "contact_types_contacts", ["contact_type_id"], "contact_types", ["id"], :name => "contact_types_contacts_contact_types_contacts_fk" )
    add_foreign_key( "discount_schedules_gizmo_types", ["discount_schedule_id"], "discount_schedules", ["id"], :name => "discount_schedules_gizmo_types_discount_schedules_fk" )
    add_foreign_key( "discount_schedules_gizmo_types", ["gizmo_type_id"], "gizmo_types", ["id"], :name => "discount_schedules_gizmo_types_gizmo_types_fk" )
    add_foreign_key( "donations", ["contact_id"], "contacts", ["id"], :name => "donations_contacts_fk" )
    add_foreign_key( "gizmo_events", ["donation_id"], "donations", ["id"], :name => "gizmo_events_donations_fk" )
    add_foreign_key( "gizmo_events", ["sale_id"], "sales", ["id"], :name => "gizmo_events_sales_fk" )
    add_foreign_key( "gizmo_events", ["disbursement_id"], "disbursements", ["id"], :name => "gizmo_events_disbursements_fk" )
    add_foreign_key( "gizmo_events", ["recycling_id"], "recyclings", ["id"], :name => "gizmo_events_recyclings_fk" )
    add_foreign_key( "gizmo_events", ["gizmo_type_id"], "gizmo_types", ["id"], :name => "gizmo_events_gizmo_types_fk" )
    add_foreign_key( "gizmo_events", ["gizmo_context_id"], "gizmo_contexts", ["id"], :name => "gizmo_events_gizmo_contexts_fk" )
    add_foreign_key( "gizmo_contexts_gizmo_typeattrs", ["gizmo_context_id"], "gizmo_contexts", ["id"], :name => "gizmo_contexts_gizmo_typeattrs_gizmo_contexts_fk" )
    add_foreign_key( "gizmo_contexts_gizmo_typeattrs", ["gizmo_typeattr_id"], "gizmo_typeattrs", ["id"], :name => "gizmo_contexts_gizmo_typeattrs_gizmo_typeattrs_fk" )

    add_foreign_key( "gizmo_contexts_gizmo_types", ["gizmo_context_id"], "gizmo_contexts", ["id"], :name => "gizmo_contexts_gizmo_types_gizmo_contexts_fk" )
    add_foreign_key( "gizmo_contexts_gizmo_types", ["gizmo_type_id"], "gizmo_types", ["id"], :name => "gizmo_contexts_gizmo_types_gizmo_types_fk" )
    add_foreign_key( "gizmo_events_gizmo_typeattrs", ["gizmo_event_id"], "gizmo_events", ["id"], :name => "gizmo_events_gizmo_typeattrs_gizmo_events_fk" )
    add_foreign_key( "gizmo_events_gizmo_typeattrs", ["gizmo_typeattr_id"], "gizmo_typeattrs", ["id"], :name => "gizmo_events_gizmo_typeattrs_gizmo_typeattrs_fk" )
    add_foreign_key( "gizmo_typeattrs", ["gizmo_type_id"], "gizmo_types", ["id"], :name => "gizmo_typeattrs_gizmo_types_fk" )
    add_foreign_key( "gizmo_typeattrs", ["gizmo_attr_id"], "gizmo_attrs", ["id"], :name => "gizmo_typeattrs_gizmo_attrs_fk" )
    add_foreign_key( "gizmo_types", ["parent_id"], "gizmo_types", ["id"], :name => "gizmo_types_parent_fk" )
    add_foreign_key( "payments", ["payment_method_id"], "payment_methods", ["id"], :name => "payments_payment_methods_fk" )
    add_foreign_key( "sales", ["contact_id"], "contacts", ["id"], :name => "sales_contacts_fk" )
    add_foreign_key( "sales", ["discount_schedule_id"], "discount_schedules", ["id"], :name => "sales_discount_schedules_fk" )
    add_foreign_key( "volunteer_task_types", ["parent_id"], "volunteer_task_types", ["id"], :name => "volunteer_task_types_parent_fk" )
    add_foreign_key( "volunteer_tasks", ["contact_id"], "contacts", ["id"], :name => "volunteer_tasks_contacts_fk" )
  end

  def self.down
    remove_foreign_key( "contact_method_types", "contact_method_types_parent_id_fk" )
    remove_foreign_key( "contact_types_contacts", "contact_types_contacts_contacts_fk" )
    remove_foreign_key( "contact_types_contacts", "contact_types_contacts_contact_types_contacts_fk" )
    remove_foreign_key( "discount_schedules_gizmo_types", "discount_schedules_gizmo_types_discount_schedules_fk" )
    remove_foreign_key( "discount_schedules_gizmo_types", "discount_schedules_gizmo_types_gizmo_types_fk" )
    remove_foreign_key( "donations", "donations_contacts_fk" )
    remove_foreign_key( "gizmo_events", "gizmo_events_donations_fk" )
    remove_foreign_key( "gizmo_events", "gizmo_events_sales_fk" )
    remove_foreign_key( "gizmo_events", "gizmo_events_disbursements_fk" )
    remove_foreign_key( "gizmo_events", "gizmo_events_recyclings_fk" )
    remove_foreign_key( "gizmo_events", "gizmo_events_gizmo_types_fk" )
    remove_foreign_key( "gizmo_events", "gizmo_events_gizmo_contexts_fk" )
    remove_foreign_key( "gizmo_contexts_gizmo_typeattrs", "gizmo_contexts_gizmo_typeattrs_gizmo_contexts_fk" )
    remove_foreign_key( "gizmo_contexts_gizmo_typeattrs", "gizmo_contexts_gizmo_typeattrs_gizmo_typeattrs_fk" )
    remove_foreign_key( "gizmo_contexts_gizmo_types", "gizmo_contexts_gizmo_types_gizmo_contexts_fk" )
    remove_foreign_key( "gizmo_contexts_gizmo_types", "gizmo_contexts_gizmo_types_gizmo_types_fk" )
    remove_foreign_key( "gizmo_events_gizmo_typeattrs", "gizmo_events_gizmo_typeattrs_gizmo_events_fk" )
    remove_foreign_key( "gizmo_events_gizmo_typeattrs", "gizmo_events_gizmo_typeattrs_gizmo_typeattrs_fk" )
    remove_foreign_key( "gizmo_typeattrs", "gizmo_typeattrs_gizmo_types_fk" )
    remove_foreign_key( "gizmo_typeattrs", "gizmo_typeattrs_gizmo_attrs_fk" )
    remove_foreign_key( "gizmo_types", "gizmo_types_parent_fk" )
    remove_foreign_key( "payments", "payments_payment_methods_fk" )
    remove_foreign_key( "sales", "sales_contacts_fk" )
    remove_foreign_key( "sales", "sales_discount_schedules_fk" )
    remove_foreign_key( "volunteer_task_types", "volunteer_task_types_parent_fk" )
    remove_foreign_key( "volunteer_tasks", "volunteer_tasks_contacts_fk" )
  end
end
