#!/bin/sh

# TODO: move to private dir

# in crontab:
# */10 * * * * ryan52 flock -n /tmp/generated-822 -c /home/ryan52/fgdb.rb/script/rt/generated-822

set -e

exec >/dev/null 2>/dev/null

cd `dirname $0`/../../

{ ./script/rt/to-dctrl "(Owner = 'ryan52' OR Queue = 'ASSAction' OR Queue = 'ASSDiscussion' OR Queue = 'Coding' OR Queue = 'Technocrats' OR Queue = 'Distro') AND (Status = 'open' OR Status = 'new' OR Status = 'stalled' OR Status = 'pending')"; echo; echo "# Generated at $(date -R)"; } | ./script/update-devel-data/under-myagent ssh llama sponge public_html/rt.822
